### ISSUE TITLE
Add arbitrary transactions as coinbase inputs at a given block height

### ISSUE THREAD

**Issue by heyrhett** [BTCPrivate/BitcoinPrivate#3] opened 2017-12-25 12:18 UTC
Full nodes check Transactions and Blocks for validity.

Many of the validity checks are skipped for Coinbase transactions, but a Block check is made to ensure that there is only 1 Coinbase transaction per block.  Both of these checks happen in main.cpp.  I have included screenshots here.

What we want to do is:

1. For a given Block Height, X, allow the block size to be larger.
2. Include any number of transactions as coinbase inputs
3. Include arbitrary values as coinbase inputs (from a file)

This means that miners will be mining, and at block X, they will create 1 large block will an arbitrary number of coinbase inputs with arbitrary values.

After that, mining will resume as normal.

Miners will download the hard fork before block X, all miners that agree to run the fork software will continue on their node, while non-upgraded miner will continue mining on the pre-fork code.

<img width="787" alt="screen shot 2017-12-25 at 6 09 46 am" src="https://user-images.githubusercontent.com/2388024/34339547-4aa1060a-e93b-11e7-9214-ed2f10706b0a.png">
<img width="641" alt="screen shot 2017-12-25 at 6 08 10 am" src="https://user-images.githubusercontent.com/2388024/34339548-4aaf8f18-e93b-11e7-8ab7-d83fab72a202.png">

**Comment by airk42** [comment] 2017-12-27 07:16
If no one is working on it, I can take it

**Comment by heyrhett** [comment] 2017-12-27 08:13
Added you as a collaborator, then I'll assign you.  This is the most critical development blocker right now, so we should have regular meetings for all the developers working on it.

**Comment by Mrwh0** [comment] 2017-12-27 08:16
i could help too .

**Comment by heyrhett** [comment] 2017-12-27 08:24
Great, so a little more details about how I think we should do this

1. We announce a Bitcoin snapshot date (allow people time to move coins to private non-segwit wallets)
2. We take the snapshot at the given date
3. Create fork that reduces difficulty at block X and adds 1000 coinbase inputs per block for 65,000 blocks (65M total addresses).
4. Have a small set of miners mine with this code.  It will require a large input file from the Bitcoin Snapshot.
5. Create a new hard fork that simply uses a checkpoint at a given block height, and no longer requires the bitcoin Snapshot.
6. Miners do a second upgrade to that.
7. We monitor the network and tell exchanges and everyone else when it is safe to enable the live Bitcoin Private wallets.

**Comment by Mrwh0** [comment] 2017-12-27 08:53
X block max size ?

**Comment by heyrhett** [comment] 2017-12-27 08:59
X is the block height we choose in Zclassic to do the fork.  Miners download the code before block X.

I think we should keep the block size limit of 2MB for all blocks.

**Comment by Mrwh0** [comment] 2017-12-27 09:02
i just asking because max size variable is on our way . good 2M im setting
env. need few hours to start on main .

**Comment by airk42** [comment] 2017-12-27 16:35
@heyrhett couple questions: 
1. so, now you don't want to have a single big block with all coinbase inputs (as per your first comment) and instead there are will be 65K of blocks with 1000 coinbase inputs per block?
2. is this issues (#3) is to cover only checks for these artificial blocks or for creating these blocks as well?

**Comment by airk42** [comment] 2017-12-27 17:57
Here is a check for multiple coinbase transactions per block

```
diff --git a/src/main.cpp b/src/main.cpp
index 31189521..8dea8426 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -71,6 +71,13 @@ size_t nCoinCacheUsage = 5000 * 300;
 uint64_t nPruneTarget = 0;
 bool fAlerts = DEFAULT_ALERTS;

+#define MAX_FORK_BLOCK_SIZE MAX_BLOCK_SIZE
+#define FORK_BLOCK_HEIGHT_START 1000000
+#define FORK_BLOCK_HEIGHT_END FORK_BLOCK_HEIGHT_START + 65000
+bool bForking = false;
+unsigned int fCoinbasePerBlock = 1;
+
+
 /** Fees smaller than this (in satoshi) are considered zero fee (for relaying and mining) */
 CFeeRate minRelayTxFee = CFeeRate(DEFAULT_MIN_RELAY_TX_FEE);

@@ -3029,10 +3036,9 @@ bool CheckBlock(const CBlock& block, CValidationState& state,
         return state.DoS(100, error("CheckBlock(): first tx is not coinbase"),
                          REJECT_INVALID, "bad-cb-missing");
     for (unsigned int i = 1; i < block.vtx.size(); i++)
-        if (block.vtx[i].IsCoinBase())
+        if (block.vtx[i].IsCoinBase() && i >= fCoinbasePerBlock)
             return state.DoS(100, error("CheckBlock(): more than one coinbase"),
                              REJECT_INVALID, "bad-cb-multiple");
-
     // Check transactions
     BOOST_FOREACH(const CTransaction& tx, block.vtx)
         if (!CheckTransaction(tx, state, verifier))
@@ -3289,6 +3295,13 @@ bool TestBlockValidity(CValidationState &state, const CBlock& block, CBlockIndex
     // NOTE: CheckBlockHeader is called by CheckBlock
     if (!ContextualCheckBlockHeader(block, state, pindexPrev))
         return false;
+
+    unsigned int nHeight = pindexPrev->nHeight + 1;
+    bForking = (nHeight >= FORK_BLOCK_HEIGHT_START && nHeight < FORK_BLOCK_HEIGHT_END);
+    if (bForking){
+        fCoinbasePerBlock = 1000;
+    }
+
     if (!CheckBlock(block, state, verifier, fCheckPOW, fCheckMerkleRoot))
         return false;
     if (!ContextualCheckBlock(block, state, pindexPrev))

```

If we DO want to check for bigger block size for forked transactions, I guess it can be done, smth like this:
unsigned int fBlockSize = MAX_BLOCK_SIZE;

...

if (bForking){
       fCoinbasePerBlock = 1000;
       fBlockSize = MAX_FORK_BLOCK_SIZE;
   }
...

   // Size limits
    if (block.vtx.empty() || block.vtx.size() > fBlockSize || ::GetSerializeSize(block, SER_NETWORK, PROTOCOL_VERSION) > fBlockSize)
        return state.DoS(100, error("CheckBlock(): size limits failed"),
                         REJECT_INVALID, "bad-blk-length");

**Comment by heyrhett** [comment] 2017-12-28 12:52
@airk42 

> 1. so, now you don't want to have a single big block with all coinbase inputs (as per your first comment) and instead there are will be 65K of blocks with 1000 coinbase inputs per block?
>
Yes, I think we should keep the block size limit under 2 MB as it is set now.  We could have issues making a single block over 1 GB.

> 2. is this issues (#3) is to cover only checks for these artificial blocks or for creating these blocks as well?

We need to create the blocks as well.

**Comment by airk42** [comment] 2017-12-28 17:03
OK then, I am on it. There is not need in label "help wanted"
I will target to have all it coded before the end of the year.

**Comment by airk42** [comment] 2017-12-28 17:05
Also, I think we need to create branch for the code inserting coinbases.

**Comment by heyrhett** [comment] 2017-12-28 17:06
Is there a place I can chat with you?  Telegram, Twitter?

**Comment by Mrwh0** [comment] 2017-12-28 17:13
im on that too please open discord channel or irc somewhere

**Comment by heyrhett** [comment] 2017-12-28 17:17
We're going to need to see daily progress on this, and it's also something that should require multiple people to review, so we should discuss updates on this daily somewhere.

**Comment by airk42** [comment] 2017-12-28 17:23
https://t.me/airk42

We can create private Telegram chat or use Discord - discordapp.com

**Comment by Mrwh0** [comment] 2017-12-28 17:30
i don't care about the bounty i just wanted this done so let me know where
i go.

**Comment by airk42** [comment] 2017-12-28 17:35
https://discord.gg/y65DfQ

**Comment by kennethffx2** [comment] 2017-12-30 19:56
How's this looking boys? This issue being solved is my deciding factor in buying $30,000 worth of Zclassic.

**Comment by GildedHonour** [comment] 2017-12-30 21:27
I'll be interested to take it. Bounty?

**Comment by airk42** [comment] 2017-12-31 07:31
It is work in progress, but it is close

**Comment by GildedHonour** [comment] 2017-12-31 13:58
Are there other issues-bounties I can take?

**Comment by akx20000a** [comment] 2018-01-02 11:23
@heyrhett  Isn't 1-Gig Block would be better than mining 65K blocks?

**Comment by starrymoonlight** [comment] 2018-01-05 00:44
> We announce a Bitcoin snapshot date (allow people time to move coins to private non-segwit wallets)

Can't BitcoinPrivate support Segwit addresses? If not, that will be a negative. Bitcoin Gold worked on Segwit addresses.

**Comment by SazzadGit** [comment] 2018-01-05 04:42
how do we get BTCP if i have zclassic in my Bittrex?

**Comment by gktown** [comment] 2018-01-08 02:58
Puttin' a +1 ZCL on the bounty.

**Comment by GildedHonour** [comment] 2018-01-08 03:01
Are there other issues-bounties I can take?

**Comment by airk42** [comment] 2018-01-08 03:08
The issue is ready to be closed - all code is merged into cb-input branch

Description -->

This is forking version of the BTCPrivate node
Its major and the only goal is to insert and verify BTC utxo into ZClassic blockchain as blocks with multiple (10000 by default) Coinbases translocation.

**There are 4 additional configuration parameters to control the behavior of that node:**

1. utxo-path=<path to the folder with utxo files>

This is the most important parameter - it points to the location of utxo files
These utxo files MUST be named as such - "utxo-nnnnn.bin", where nnnnn is number from 00001 to (number-of-btc-utxo/10000) and by default have 10K utxo transactions as raw records
Example - utxo-00001.bin, utxo-00002.bin and so forth

2. fork-startheight=n
Chain height when forking will start - default is MUST be set in the code, this parameter should be used only for testing

3. fork-heightrange=n
Range of fork - basically the number of utxo files to process - default 65K

4. fork-cbperblock=n
Number of CB's in the block and number rof records in the utxo file - default 10K

**This version of node can work in three different modes:**
1. Mine fork blocks with utxo transactions using built in miner
2. Verify fork blocks
3. Do nothing

Mode 1 and 2 reuire the the utxo files!!!

**How to enable corresponding mode**
1. Mining mode
a. put following into the config file (btcprivate.conf):

    gen=1
    utxo-path=<path-to-utxo-files>

Note: Start height Must be set in the code, but it can also be set via fork-startheight config parameter 

b. start the node
c. When tip of the chain will get into the range (**fork-startheight <= tip < fork-startheight+fork-heightrange**), miner starts to create fork blocks with only CB transactions from utxo files.
 One block from each file. And will "mine" them with the reduced difficulty ~ 1 sec per block.
 In this mode miner can only creates fork blocks from files - if chain tip is still inside the range, but there are no files - miner will not mine anything else.
 At each moment miner tries to create block from the file with the name matching current chain height.

_Example_: 

Let's say the fork height set in the code as 300000; range as 65K and CB per block as 10K
While chain height is bellow 300000 - miner is trying to mine using normal algo (so it most probably doesn't mine anything)
When block height become 300000 - miner creates fork block:
Miner opens file - utxo-000001.bin, reads it and creates fork block 300 001 with 10K CB's (or whatever number of record was in the file, but <= 10K)
Miner then "mines" block and sends it to the network
Then it takes the next value of chain height and search for the "matching" file.
In this example, miner will create fork blocks while chain tip is between 300000 and 364999 from utxo files as such:
300 001 -> uto-000001.bin
300 002 -> utxo-000002.bin
...
300 123 -> utxo-000123.bin
...
306 500 -> utxo-065000.bin

2. Verification mode
a. put following into the config file (btcprivate.conf):

    utxo-path=<path-to-utxo-files>

Note: Start height Must be set in the code, but it can also be set via fork-startheight config parameter 

b. start the node
c. When tip of the chain will get into the range (**fork-startheight < tip < fork-startheight+fork-heightrange**), node starts to compare the content of all newly received blocks with the content of utxo files.
If block and file match - node accepts block; if they are not - node rejects block. 

_Example_: 

Let's say the fork height set in the code as 300000; range as 65K and CB per block as 10K
While chain height is bellow 300001 - node is not doing anything different from the usual ZClassic node.
When the node receives the block that when accepted will be at height 300001 - the node perform an additional verification for newly received blocks:
Node opens utxo file - utxo-000001.bin, read it into memory and compare its records with transactions from the block # 300001
If they match - block is accepted; if not - rejected
In this example, node will do this verification for all blocks between 300001 and 365000 and checks them with utxo files as such:
300 001 -> uto-000001.bin
300 002 -> utxo-000002.bin
...
300 123 -> utxo-000123.bin
...
306 500 -> utxo-065000.bin

3. Mode 3
a. make sure utxo-path is not specified in the config file.

**Comment by gktown** [comment] 2018-01-08 03:10
Fantastic info! I stand by what I said :+1:

**Comment by andreibolkonsky** [comment] 2018-01-08 04:54
Fantastic man

**Comment by GildedHonour** [comment] 2018-01-08 05:52
@heyrhett Are there other issues-bounties I can take?

**Comment by Stonee101** [comment] 2018-01-09 23:44
This is great news! I'm impressed.

How will the utxo-123 files be deployed through the network? I assume every node must have this for mining / verifying

**Comment by dolb** [comment] 2018-01-16 08:21
You will be able to generate them from your bitcoind directly I believe.

**Closed** 2018-02-05 04:08 UTC
Labels: Bounty Offered, help wanted
